; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24213.1 

	TITLE	c:\10c\A\oe\KZOETSAA.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG13349 DB	'May 25 2017 16:13:59', 00H
	ORG $+3
$SG13350 DB	'Compile Date/Time for OE is ', 00H
_DATA	ENDS
PUBLIC	_fnTraceCompileTime@0
EXTRN	_TraceLineS@8:PROC
; Function compile flags: /Odtp
; File c:\10c\a\oe\kzoetsaa.c
_TEXT	SEGMENT
_fnTraceCompileTime@0 PROC

; 32   : {

	push	ebp
	mov	ebp, esp

; 33   :    TraceLineS( "Compile Date/Time for OE is ", __DATE__ " " __TIME__ );

	push	OFFSET $SG13349
	push	OFFSET $SG13350
	call	_TraceLineS@8

; 34   : }

	pop	ebp
	ret	0
_fnTraceCompileTime@0 ENDP
_TEXT	ENDS
END
