; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24213.1 

	TITLE	c:\10c\w\oe\ZDLLINST.C
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_g_hInstanceDLL
_BSS	SEGMENT
_g_hInstanceDLL DD 01H DUP (?)
_BSS	ENDS
PUBLIC	_DllMain@12
PUBLIC	_GetDLL_Instance@4
; Function compile flags: /Odtp
; File c:\10c\w\oe\zdllinst.c
_TEXT	SEGMENT
_vSubtask$ = 8						; size = 4
_GetDLL_Instance@4 PROC

; 54   : {

	push	ebp
	mov	ebp, esp

; 55   :    return( g_hInstanceDLL );

	mov	eax, DWORD PTR _g_hInstanceDLL

; 56   : }

	pop	ebp
	ret	4
_GetDLL_Instance@4 ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\10c\w\oe\zdllinst.c
_TEXT	SEGMENT
tv64 = -4						; size = 4
_hDLL$ = 8						; size = 4
_dwReason$ = 12						; size = 4
_lpReserved$ = 16					; size = 4
_DllMain@12 PROC

; 32   : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 33   :   switch ( dwReason )

	mov	eax, DWORD PTR _dwReason$[ebp]
	mov	DWORD PTR tv64[ebp], eax
	cmp	DWORD PTR tv64[ebp], 1
	je	SHORT $LN4@DllMain
	jmp	SHORT $LN2@DllMain
$LN4@DllMain:

; 34   :   {
; 35   :       case DLL_PROCESS_ATTACH:
; 36   :          g_hInstanceDLL = (HINSTANCE) hDLL;

	mov	ecx, DWORD PTR _hDLL$[ebp]
	mov	DWORD PTR _g_hInstanceDLL, ecx
$LN2@DllMain:

; 37   :          break;
; 38   : 
; 39   :       case DLL_THREAD_ATTACH:
; 40   :          break;
; 41   : 
; 42   :       case DLL_THREAD_DETACH:
; 43   :          break;
; 44   : 
; 45   :       case DLL_PROCESS_DETACH:
; 46   :          break;
; 47   :    }
; 48   : 
; 49   :    return( TRUE );

	mov	eax, 1

; 50   : }

	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
_DllMain@12 ENDP
_TEXT	ENDS
END
